[
	[
		["", "", "", "", "", "", "", "", ""],
		["", "", "", "", "", "", "", "", "QUARTER"],
		["", "", "", "", "", "", "", "", "OF"],
		["", "", "", "", "", "", "", "", "INSPECTION"],
		["", "", "", "", "", "", "", "", "4TH QUARTER"],
		["", "", "", "", "", "", "", "", ""],
		["", "", "", "", "", "", "", "", ""],
		["", "", "", "", "", "", "", "", ""],
		["", "", "", "", "", "", "", "", ""],
		["", "", "", "27 Bothwell Road", "", "Brighton, MA 02135", "", "", ""],
		["", "", "", "", "", "", "", "", ""],
		["CUSTOMER", "CJ Properties", "", "INSPECTION", "Sep 26, 2014", "MTHLY", false, "SEMI-AN", false],
		["PROPERTY", "Keystone Apartments", "", "DATE", "", "QRTLY", true, "ANNUAL", false],
		["ADDRESS", "151 Hallet Street", "", "SYSTEM TYPE", "", "", "", "", ""],
		["CITY", "Dorchester", "", true, "FIRE ALARM", false, "E-VAC/COMM", false, "LINE VOLTAGE"],
		["STATE", "Massachusetts", "", "Inspector:", "", "", "LICENSE #", "", ""],
		["ZIP", "02124", "", "Nate Donnelly", "", "", "A17546", "", ""],
		["SYSTEM CIRCUIT TYPE", "", "", "", "", "", "", "", ""],
		["ADDRESSABLE", "", "", "", true, "LOCAL AUTHORITY HAVING JURISDICTION", "", "", ""],
		["CONVENTIONAL", "", "", "", true, "Boston Fire Department", "", "", ""],
		["CONTROL PANEL FUNCTIONS", "", "", "", "", "", "", "", ""],
		["MANUFACTURER", "", "MODEL NO.", "NO. DETECTION CIRCUITS / SLC LOOPS", "", "", "NO. INDICATION CIRCUITS", "", ""],
		["Fire-Lite", "", "MS-9600 UDLS", "1 SLC Loop", "", "", "(2) Class A Circuits", "", ""],
		["ACTIVATION", "EACH ZONE TESTED / ADDRESS", "", "PROPER ZONE ACTIVATION / ADDRESS", "", "PROPER F.A.G.P. ACTIVATION", "", "PROPER ANNUNCIATION", ""],
		["FUNCTION", true, "", true, "", true, "", true, ""],
		["SUPERVISORY", "ZONE TROUBLE", "SIGNAL TROUBLE", "", "A/C LOSS", "BATTERY FAILURE", "", "EARTH GROUND", ""],
		["FUNCTIONS", false, true, "", true, true, "", true, ""],
		["SIGNALING", true, "ALL SOUND", false, "CODED", "EVACUATION PAGING SYSTEM", "", "", ""],
		["TYPE", false, "SELECTIVE", false, "MARCH TIME", true, "", "", ""],
		["SIGNALING", true, "HORN/STROBE", false, "BELLS", "INTERNAL COMMUNICATION SYSTEM", "", "", ""],
		["MEANS", true, "HORN", false, "SPEAKERS", "N/A", "", "", ""],
		["MUNICIPAL", "TESTED", "MASTER BOX", "", "CENTRAL STATION COMP.", "", "ACC. #", "OTHER MEANS", ""],
		["NOTIFICATION", true, true, "MB# 12-3272", true, "Wayne Acc # 65-7602", "", "", ""],
		["POWER", "C.B. LOCATION", "", "DEDICATED C.B.", "SURGE PROT.", "BATTERIES", "MODEL/QTY.", "VOLT W/LOAD", "VOLT W/A.C."],
		["SOURCE", "Panel in Maintenance Shop", "", true, false, true, "(2)12V 26AH", "", ""],
		["AUXILIARY FUNCTIONS", "", "", "", "", "", "", "", ""],
		["DOOR HOLDERS", "", "QUANTITY:", "0", "HVAC SHUTDWON", "", "", "AUTO", "N/A"],
		["N/A", "", "VOLTAGE:", "0", "N/A", "", "", "RESTART", ""],
		["SMOKE HATCH", false, "N/A", "QUANTITY", "ELEVATOR RECALL", "", "PRIMARY FLOOR", "", true],
		["N/A", false, false, "0", "N/A", "", "ALTERNATE FLOOR", "", false],
		["SMOKE EXHAUST SYSTEM", "", "", "ANNUNCIATOR PANEL", "", true, "L.E.D.", false, "GRAPHIC"],
		["N/A", "QUANTITY:", "0", true, "", true, "LCD", false, "OTHER"],
		["ADA BOOSTER PANEL", "", "", "", "", "", "", true, false],
		["", "", "", "", "", "", "", false, true],
		["POWER", "C.B. LOCATION", "", "DEDICATED C.B.", "SURGE PROT.", "BATTERIES", "MODEL/QTY.", "VOLT W/LOAD", "VOLT W/A.C."],
		["SOURCE", "", "", "N/A", "N/A", "N/A", "", "", ""],
		["SYNCHRONIZATION", "", "N/A", "SYNCH MODULE", "", "N/A", "Quantity", "", ""],
		["LOCATION(S)", "", "", "", "", "", "", "", ""],
		["2nd,3rd and 4th Floor Electrical rooms.", "", "", "", "", "", "", "", ""],
		["FIRE PUMP", "", "", "", "", "", "", "N/A", false],
		["FIRE PUMP", "", "ALARM", false, "FIRE PUMP OR PUMP CONTROLLER TROUBLE", "", "", "", true],
		[true, "", "TROUBLE", true, "", "", "", "", ""],
		["FIRE PUMP RUNNING", "", "ALARM", false, "FIRE PUMP POWER", "", "", "", true],
		[true, "", "TROUBLE", true, "FIRE PUMP AUTO POSITION", "", "", "", false],
		["TYPE OF SPRINKLER SYSTEM", "", "", "", "", "", "", "N/A", true],
		["SPRINKLER ALARM SYSTEM", "", "", "WET", true, "DRY", false, "PREACTION", false],
		["VOICE EVACUATION SYSTEM", "", "", "", "", "", "", true, false],
		["", "", "", "", "", "", "", false, true],
		["QUANTITIES", "AMPLIFIERS", "WATTAGE", "FIREFIGHTER PHONES", "", "QUANTITIES", "LOCATION", "", ""],
		["0", "N/A", "", "N/A", "", "0", "", "", ""],
		["POWER", "MODEL", "", "BATTERIES", "", "QUANTITY", "", "VOLT W/LOAD", "VOLT W/A.C."],
		["SOURCE", "", "", "N/A", "", "0", "", "", ""],
		["", "", "", "", "", "", "", "", ""],
		["", "", "", "", "", "", "", "", ""],
		["", "", "", "", "", "", "", "", ""],
		["", "", "", "", "", "", "", "", ""],
		["", "", "", "", "", "", "", "", ""],
		["", "", "", "", "", "", "", "", ""],
		["", "", "", "", "", "", "", "", ""],
		["", "", "", "", "", "", "", "", ""],
		["", "", "", "", "", "", "", "", ""],
		["", "", "", "", "", "", "", "", ""],
		["GENERAL NOTATIONS & RECOMMENDATIONS", "", "", "", "", "", "", "", ""],
		["All ADA panels are currently not supervised for power loss, opens, and ground faults. This item should be highly considered for repair due to the existing audio visual condition installed by previous (2) Contractors.", "", "", "", "", "", "", "", ""],
		["All existing initiating circuits are class B type wiring. Special note shall be made that any trouble conditions that come in on these loops should be addressed immediately, due to the possibility that if this type of existing wiring is compromised, all devices down stream will not receive voltage and are therefore inoperable.", "", "", "", "", "", "", "", ""]
	],
	[
		["Battery(ies)", "FACP", "Main electric room", false, true, false, "", "", true, "", "", "", ""],
		["Annunciator", "1st Floor", "Front entrance", false, true, false, "", "", true, "", "", "", ""],
		["Tamper Switch", "5th Floor", "Trash Rm Right", false, true, false, "M007", "1", true, "", "", "", ""],
		["Flow Switch", "5th Floor", "Trash Rm Right", true, false, false, "M007", "4", true, "", "", "", ""],
		["Tamper Switch", "4th Floor", "Trash Rm Right", false, true, false, "M012", "3", true, "", "", "", ""],
		["Flow Switch", "4th Floor", "Trash Rm Right", true, false, false, "M012", "2", true, "", "", "", ""],
		["Tamper Switch", "3rd Floor", "Trash Rm Right", false, true, false, "M009", "8", true, "", "", "", ""],
		["Flow Switch", "3rd Floor", "Trash Rm Right", true, false, false, "M009", "46", true, "", "", "", ""],
		["Tamper Switch", "2nd Floor", "Trash Rm Right", false, true, false, "M001", "37", true, "", "", "", ""],
		["Flow Switch", "2nd Floor", "Trash Rm Right", true, false, false, "M001", "58", true, "", "", "", ""],
		["Tamper Switch", "1st Floor", "Trash Rm Right", false, true, false, "M010", "", true, "", "", "", ""],
		["Flow Switch", "1st Floor", "Trash Rm Right", true, false, false, "M010", "", true, "", "", "", ""],
		["Tamper Switch", "1st Floor", "Right Hall", false, true, false, "M010", "", true, "", "", "", ""],
		["Flow Switch", "1st Floor", "Right Hall", true, false, false, "M010", "", true, "", "", "", ""],
		["Tamper Switch", "1st Floor", "compactor Rm Right", false, true, false, "M010", "", true, "", "", "", ""],
		["Flow Switch", "1st Floor", "compactor Rm Right", true, false, false, "M010", "", true, "", "", "", ""],
		["Tamper Switch", "5th Floor", "Trash Rm left", false, true, false, "M003", "", true, "", "", "", ""],
		["Flow Switch", "5th Floor", "Trash Rm left", true, false, false, "M003", "", true, "", "", "", ""],
		["Tamper Switch", "4th Floor", "Trash Rm left", false, true, false, "M008", "", true, "", "", "", ""],
		["Flow Switch", "4th Floor", "Trash Rm left", true, false, false, "M008", "", true, "", "", "", ""],
		["Tamper Switch", "3rd Floor", "Trash Rm left", false, true, false, "M002", "", true, "", "", "", ""],
		["Flow Switch", "3rd Floor", "Trash Rm left", true, false, false, "M002", "", true, "", "", "", ""],
		["Tamper Switch", "2nd Floor", "Trash Rm left", false, true, false, "M004", "", true, "", "", "", ""],
		["Flow Switch", "2nd Floor", "Trash Rm left", true, false, false, "M004", "", true, "", "", "", ""],
		["Tamper Switch", "1st Floor", "Hall left", false, true, false, "M005", "", true, "", "", "", ""],
		["Flow Switch", "1st Floor", "Hall left", true, false, false, "M005", "", true, "", "", "", ""],
		["Tamper Switch", "1st Floor", "compactor Rm left", false, true, false, "M005", "", true, "", "", "", ""],
		["Flow Switch", "1st Floor", "compactor Rm left", true, false, false, "M005", "", true, "", "", "", ""],
		["Tamper Switch", "1st Floor", "Standpipe by Stair 1", false, true, false, "M005", "", true, "", "", "", ""],
		["Tamper Switch", "1st Floor", "Standpipe left side of elevator", false, true, false, "M015", "", true, "", "", "", ""],
		["Flow Switch", "1st Floor", "Standpipe center community rm", true, false, false, "M015", "", true, "", "", "", ""],
		["Tamper Switch", "1st Floor", "Standpipe center community rm", false, false, false, "M015", "", true, "", "", "", ""],
		["Tamper Switch", "1st Floor", "Standpipe center by community rm", false, false, false, "M015", "", true, "", "", "", ""],
		["Tamper Switch", "1st Floor", "Standpipe right of elevator", false, false, false, "M015", "", true, "", "", "", ""],
		["Tamper Switch", "1st Floor", "Standpipe by stair 4", false, false, false, "M010", "", true, "", "", "", ""],
		["Tamper Switch", "1st Floor", "Main sprinkler Rm city side", false, true, false, "M014", "", true, "", "", "", ""],
		["Tamper Switch", "1st Floor", "Main Sprinkler Rm system side", false, true, false, "M014", "", true, "", "", "", ""],
		["Tamper Switch", "1st Floor", "Main sprinkler Rm valve city side of pump", false, true, false, "M014", "", true, "", "", "", ""],
		["Tamper Switch", "1st Floor", "Main sprinkler Rm discharge side", false, true, false, "M014", "", true, "", "", "", ""],
		["Tamper Switch", "1st Floor", "Main sprinkler Rm city side bypass", false, true, false, "M014", "", true, "", "", "", ""],
		["Tamper Switch", "1st Floor", "Main sprinkler Rm system side bypass", false, true, false, "M014", "", true, "", "", "", ""],
		["Fire Pump Control", "1st Floor", "Main sprinkler Rm fire pump shutdown", false, true, false, "M014", "", true, "", "", "", ""],
		["Heat Detector", "4th Floor", "Apartment 401", true, false, false, "M008", "", true, "", "", "", ""],
		["Horn Strobe", "4th Floor", "Apartment 401", true, false, false, "", "", true, "", "", "", ""],
		["Smoke Detector", "4th Floor", "Hall By 401 and Storage", true, false, false, "M008", "", true, "", "", "", ""],
		["Heat Detector", "4th Floor", "Apartment 403", true, false, false, "M008", "", true, "", "", "", ""],
		["Horn", "4th Floor", "Apartment 403", true, false, false, "", "", true, "", "", "", ""],
		["Heat Detector", "4th Floor", "Apartment 405", true, false, false, "M008", "", true, "", "", "", ""],
		["Horn", "4th Floor", "Apartment 405", true, false, false, "", "", true, "", "", "", ""],
		["Horn Strobe", "4th Floor", "Hall By 401", true, false, false, "", "", true, "", "", "", ""],
		["Heat Detector", "4th Floor", "Apartment 402", true, false, false, "M008", "", true, "", "", "", ""],
		["Horn", "4th Floor", "Apartment 402", true, false, false, "", "", true, "", "", "", ""],
		["Pull Station", "4th Floor", "By Stair 1", true, false, false, "M008", "", true, "", "", "", ""],
		["Smoke Detector", "4th Floor", "Stair 1", true, false, false, "M008", "", true, "", "", "", ""],
		["Heat Detector", "4th Floor", "Apartment 404", true, false, false, "M008", "", true, "", "", "", ""],
		["Horn", "4th Floor", "Apartment 404", true, false, false, "", "", true, "", "", "", ""],
		["Smoke Detector", "4th Floor", "Hall by 404", true, false, false, "M008", "", true, "", "", "", ""],
		["Smoke Detector", "4th Floor", "Hall Between 407 and 406", true, false, false, "M008", "", true, "", "", "", ""],
		["Heat Detector", "4th Floor", "Apartment 406", true, false, false, "M008", "", true, "", "", "", ""],
		["Horn", "4th Floor", "Apartment 406", true, false, false, "", "", true, "", "", "", ""],
		["Heat Detector", "4th Floor", "Apartment 407", true, false, false, "M008", "", true, "", "", "", ""],
		["Horn", "4th Floor", "Apartment 407", true, false, false, "", "", true, "", "", "", ""],
		["Horn Strobe", "4th Floor", "Hall Between 407 and 409", true, false, false, "", "", true, "", "", "", ""],
		["Horn Strobe", "4th Floor", "Hall Between 406 and 408", true, false, false, "", "", true, "", "", "", ""],
		["Smoke Detector", "4th Floor", "Hall Between 408 and 409", true, false, false, "M008", "", true, "", "", "", ""],
		["Heat Detector", "4th Floor", "Apartment 408", true, false, false, "M008", "", true, "", "", "", ""],
		["Horn", "4th Floor", "Apartment 408", true, false, false, "", "", true, "", "", "", ""],
		["Heat Detector", "4th Floor", "Apartment 409", true, false, false, "M008", "", true, "", "", "", ""],
		["Horn", "4th Floor", "Apartment 409", true, false, false, "", "", true, "", "", "", ""],
		["Smoke Detector", "4th Floor", "Hall Between 410 and 411", true, false, false, "M008", "", true, "", "", "", ""],
		["Horn Strobe", "4th Floor", "Hall Between 413 and 411", true, false, false, "", "", true, "", "", "", ""],
		["Horn Strobe", "4th Floor", "Hall Between 412 and Storage", true, false, false, "", "", true, "", "", "", ""],
		["Heat Detector", "4th Floor", "Apartment 410", true, false, false, "M008", "", true, "", "", "", ""],
		["Horn", "4th Floor", "Apartment 410", true, false, false, "", "", true, "", "", "", ""],
		["Heat Detector", "4th Floor", "Apartment 411", true, false, false, "M008", "", true, "", "", "", ""],
		["Horn", "4th Floor", "Apartment 411", true, false, false, "", "", true, "", "", "", ""],
		["Smoke Detector", "4th Floor", "Hall Between 412 and 413", true, false, false, "M008", "", true, "", "", "", ""],
		["Heat Detector", "4th Floor", "Apartment 412", true, false, false, "M008", "", true, "", "", "", ""],
		["Horn", "4th Floor", "Apartment 412", true, false, false, "", "", true, "", "", "", ""],
		["Heat Detector", "4th Floor", "Apartment 413", true, false, false, "M008", "", true, "", "", "", ""],
		["Horn", "4th Floor", "Apartment 413", true, false, false, "", "", true, "", "", "", ""],
		["Heat Detector", "4th Floor", "Apartment 414", true, false, false, "M008", "", true, "", "", "", ""],
		["Horn Strobe", "4th Floor", "Apartment 414", true, false, false, "", "", true, "", "", "", ""],
		["Smoke Detector", "4th Floor", "Hall Between 415 and Storage", true, false, false, "M008", "", true, "", "", "", ""],
		["Heat Detector", "4th Floor", "Apartment 415", true, false, false, "M008", "", true, "", "", "", ""],
		["Horn", "4th Floor", "Apartment 415", true, false, false, "", "", true, "", "", "", ""],
		["Heat Detector", "4th Floor", "Trash Rm Left", true, false, false, "M008", "", true, "", "", "", ""],
		["Smoke Detector", "4th Floor", "Electrical Rm Left", true, false, false, "D006", "", true, "", "", "", ""],
		["Heat Detector", "4th Floor", "Electrical Rm Left", true, false, false, "M008", "", true, "", "", "", ""],
		["Smoke Detector", "4th Floor", "Hall By 417", true, false, false, "M008", "", true, "", "", "", ""],
		["Pull Station", "4th Floor", "Hall By 417", true, false, false, "M008", "", true, "", "", "", ""],
		["Horn Strobe", "4th Floor", "Hall By 417", true, false, false, "", "", true, "", "", "", ""],
		["Heat Detector", "4th Floor", "Apartment 417", true, false, false, "M008", "", true, "", "", "", ""],
		["Horn", "4th Floor", "Apartment 417", true, false, false, "", "", true, "", "", "", ""],
		["Smoke Detector", "4th Floor", "Elevator Seating Area", true, false, false, "M008", "", true, "", "", "", ""],
		["Smoke Detector", "4th Floor", "Between 416 and 419", true, false, false, "M013", "", true, "", "", "", ""],
		["Horn Strobe", "4th Floor", "Between 416 and 418", true, false, false, "", "", true, "", "", "", ""],
		["Heat Detector", "4th Floor", "Apartment 416", true, false, false, "M013", "", true, "", "", "", ""],
		["Horn", "4th Floor", "Apartment 416", true, false, false, "", "", true, "", "", "", ""],
		["Heat Detector", "4th Floor", "Apartment 419", true, false, false, "M013", "", true, "", "", "", ""],
		["Horn", "4th Floor", "Apartment 419", true, false, false, "", "", true, "", "", "", ""],
		["Smoke Detector", "4th Floor", "Hall Between 418 and 421", true, false, false, "", "", true, "", "", "", ""],
		["Heat Detector", "4th Floor", "Apartment 418", true, false, false, "M013", "", true, "", "", "", ""],
		["Horn", "4th Floor", "Apartment 418", true, false, false, "", "", true, "", "", "", ""],
		["Heat Detector", "4th Floor", "Apartment 421", true, false, false, "M013", "", true, "", "", "", ""],
		["Horn", "4th Floor", "Apartment 421", true, false, false, "", "", true, "", "", "", ""],
		["Horn Strobe", "4th Floor", "Hall Between 421 and 423", true, false, false, "", "", true, "", "", "", ""],
		["Heat Detector", "4th Floor", "Apartment 420", true, false, false, "M013", "", true, "", "", "", ""],
		["Horn", "4th Floor", "Apartment 420", true, false, false, "", "", true, "", "", "", ""],
		["Heat Detector", "4th Floor", "Apartment 423", true, false, false, "M013", "", true, "", "", "", ""],
		["Horn", "4th Floor", "Apartment 423", true, false, false, "", "", true, "", "", "", ""],
		["Smoke Detector", "4th Floor", "Hall By 425", true, false, false, "M013", "", true, "", "", "", ""],
		["Heat Detector", "4th Floor", "Apartment 425", true, false, false, "M013", "", true, "", "", "", ""],
		["Horn", "4th Floor", "Apartment 425", true, false, false, "", "", true, "", "", "", ""],
		["Horn Strobe", "4th Floor", "By Laundry Room", true, false, false, "", "", true, "", "", "", ""],
		["Heat Detector", "4th Floor", "Laundry Room", true, false, false, "M013", "", true, "", "", "", ""],
		["Pull Station", "4th Floor", "By Stair 2", true, false, false, "M013", "", true, "", "", "", ""],
		["Smoke Detector", "4th Floor", "Stair 2", true, false, false, "M013", "", true, "", "", "", ""],
		["Smoke Detector", "4th Floor", "Hall By Janitor Closet and Storage Room", true, false, false, "M013", "", true, "", "", "", ""],
		["Pull Station", "4th Floor", "Hall By 422 and Stair 3", true, false, false, "", "", true, "", "", "", ""],
		["Heat Detector", "4th Floor", "Apartment 422", true, false, false, "M013", "", true, "", "", "", ""],
		["Horn", "4th Floor", "Apartment 422", true, false, false, "", "", true, "", "", "", ""],
		["Smoke Detector", "4th Floor", "Hall By 429", true, false, false, "M013", "", true, "", "", "", ""],
		["Smoke Detector", "4th Floor", "Stair 3", true, false, false, "M013", "", true, "", "", "", ""],
		["Smoke Detector", "4th Floor", "Hall by 427", true, false, false, "M013", "", true, "", "", "", ""],
		["Heat Detector", "4th Floor", "Apartment 427", true, false, false, "M013", "", true, "", "", "", ""],
		["Horn", "4th Floor", "Apartment 427", true, false, false, "", "", true, "", "", "", ""],
		["Heat Detector", "4th Floor", "Apartment 424", true, false, false, "M013", "", true, "", "", "", ""],
		["Horn", "4th Floor", "Apartment 424", true, false, false, "", "", true, "", "", "", ""],
		["Heat Detector", "4th Floor", "Apartment 429", true, false, false, "M013", "", true, "", "", "", ""],
		["Horn", "4th Floor", "Apartment 429", true, false, false, "", "", true, "", "", "", ""],
		["Smoke Detector", "4th Floor", "Hall Between 426 and 431", true, false, false, "", "", true, "", "", "", ""],
		["Horn Strobe", "4th Floor", "Hall Between 429 and 431", true, false, false, "", "", true, "", "", "", ""],
		["Heat Detector", "4th Floor", "Apartment 431", true, false, false, "M013", "", true, "", "", "", ""],
		["Horn", "4th Floor", "Apartment 431", true, false, false, "", "", true, "", "", "", ""],
		["Heat Detector", "4th Floor", "Apartment 426", true, false, false, "M013", "", true, "", "", "", ""],
		["Horn", "4th Floor", "Apartment 426", true, false, false, "", "", true, "", "", "", ""],
		["Pull Station", "4th Floor", "Right Hall Fire Doors", true, false, false, "M012", "", true, "", "", "", ""],
		["Horn Strobe", "4th Floor", "Right Hall Fire Doors", true, false, false, "", "", true, "", "", "", ""],
		["Smoke Detector", "4th Floor", "Hall between 428 and 433", true, false, false, "M012", "", true, "", "", "", ""],
		["Horn Strobe", "4th Floor", "Hall by 433", true, false, false, "", "", true, "", "", "", ""],
		["Heat Detector", "4th Floor", "Apartment 428", true, false, false, "M012", "", true, "", "", "", ""],
		["Horn", "4th Floor", "Apartment 428", true, false, false, "", "", true, "", "", "", ""],
		["Heat Detector", "4th Floor", "Apartment 428", true, false, false, "M012", "", true, "", "", "", ""],
		["Horn", "4th Floor", "Apartment 428", true, false, false, "", "", true, "", "", "", ""],
		["Heat Detector", "4th Floor", "Apartment 428", true, false, false, "M012", "", true, "", "", "", ""],
		["Horn", "4th Floor", "Apartment 428", true, false, false, "", "", true, "", "", "", ""],
		["Smoke Detector", "4th Floor", "Hall by 435", true, false, false, "M012", "", true, "", "", "", ""],
		["Heat Detector", "4th Floor", "Apartment 435", true, false, false, "M012", "", true, "", "", "", ""],
		["Horn Strobe", "4th Floor", "Apartment 435 Entry", true, false, false, "", "", true, "", "", "", ""],
		["Ceiling Strobe", "4th Floor", "Apartment 435 Bathroom", true, false, false, "", "", true, "", "", "", ""],
		["Ceiling Horn Strobe", "4th Floor", "Apartment 435 Bedroom", true, false, false, "", "", true, "", "", "", ""],
		["Smoke Detector", "4th Floor", "Hall by Electrical Room", true, false, false, "M012", "", true, "", "", "", ""],
		["Heat Detector", "4th Floor", "Apartment 430", true, false, false, "M012", "", true, "", "", "", ""],
		["Horn", "4th Floor", "Apartment 430", true, false, false, "", "", true, "", "", "", ""],
		["Smoke Detector", "4th Floor", "Elevator Seating Area", true, false, false, "M012", "", true, "", "", "", ""],
		["Smoke Detector", "4th Floor", "Electrical Rm Right", true, false, false, "M012", "", true, "", "", "", ""],
		["Heat Detector", "4th Floor", "Electrical Rm Right", true, false, false, "M012", "", true, "", "", "", ""],
		["Battery(ies)", "4th Floor", "Electrical Rm Right (ADA)", true, false, false, "", "", true, "TOP", "", "", ""],
		["Battery(ies)", "4th Floor", "Electrical Rm Right (ADA)", true, false, false, "", "", false, "CENTER= due to low ah ratings. (2) 12v 7ah", "", "", ""],
		["Battery(ies)", "4th Floor", "Electrical Rm Right (ADA)", true, false, false, "", "", false, "BOTTOM= due to low ah ratings. (2) 12v 7ah", "", "", ""],
		["Horn Strobe", "4th Floor", "Hall by Apartment 437", true, false, false, "", "", true, "", "", "", ""],
		["Heat Detector", "4th Floor", "Trash Rm Right", true, false, false, "M012", "", false, "Dmaged. Convent. 135.", "", "", ""],
		["Heat Detector", "4th Floor", "Apartment 437", true, false, false, "M012", "", true, "", "", "", ""],
		["Horn", "4th Floor", "Apartment 437", true, false, false, "", "", true, "", "", "", ""],
		["Smoke Detector", "4th Floor", "Hall By Apartment 432", true, false, false, "M012", "", true, "", "", "", ""],
		["Heat Detector", "4th Floor", "Apartment 432", true, false, false, "M012", "", true, "", "", "", ""],
		["Horn", "4th Floor", "Apartment 432", true, false, false, "", "", true, "", "", "", ""],
		["Heat Detector", "4th Floor", "Apartment 439", true, false, false, "M012", "", true, "", "", "", ""],
		["Horn Strobe", "4th Floor", "Apartment 439 Entry", true, false, false, "", "", true, "", "", "", ""],
		["Ceiling Strobe", "4th Floor", "Apartment 439 Bathroom", true, false, false, "", "", true, "", "", "", ""],
		["Ceiling Horn Strobe", "4th Floor", "Apartment 439 Bedroom", true, false, false, "", "", true, "", "", "", ""],
		["Smoke Detector", "4th Floor", "Hall By Apartment 434", true, false, false, "", "", true, "", "", "", ""],
		["Heat Detector", "4th Floor", "Apartment 432", true, false, false, "M012", "", true, "", "", "", ""],
		["Horn Strobe", "4th Floor", "Apartment 432 Entry", true, false, false, "", "", true, "", "", "", ""],
		["Ceiling Strobe", "4th Floor", "Apartment 432 Bathroom", true, false, false, "", "", true, "", "", "", ""],
		["Ceiling Horn Strobe", "4th Floor", "Apartment 432 Bedroom", true, false, false, "", "", true, "", "", "", ""],
		["Heat Detector", "4th Floor", "Apartment 441", true, false, false, "M012", "", true, "", "", "", ""],
		["Horn Strobe", "4th Floor", "Apartment 441", true, false, false, "", "", true, "", "", "", ""],
		["Smoke Detector", "4th Floor", "By Apartment 436", true, false, false, "M012", "", true, "", "", "", ""],
		["Horn Strobe", "4th Floor", "Hall Between 441 and 443", true, false, false, "", "", true, "", "", "", ""],
		["Heat Detector", "4th Floor", "Apartment 436", true, false, false, "M012", "", true, "", "", "", ""],
		["Horn Strobe", "4th Floor", "Apartment 436 Entry", true, false, false, "", "", true, "", "", "", ""],
		["Ceiling Strobe", "4th Floor", "Apartment 436 Bathroom", true, false, false, "", "", true, "", "", "", ""],
		["Ceiling Horn Strobe", "4th Floor", "Apartment 436 Bedroom", true, false, false, "", "", true, "", "", "", ""],
		["Heat Detector", "4th Floor", "Apartment 443", true, false, false, "M012", "", true, "", "", "", ""],
		["Horn", "4th Floor", "Apartment 443", true, false, false, "", "", true, "", "", "", ""],
		["Smoke Detector", "4th Floor", "Hall By apartment 448", true, false, false, "", "", true, "", "", "", ""],
		["Horn Strobe", "4th Floor", "Hall By apartment 448", true, false, false, "", "", true, "", "", "", ""],
		["Heat Detector", "4th Floor", "Apartment 438", true, false, false, "M012", "", true, "", "", "", ""],
		["Horn Strobe", "4th Floor", "Apartment 438", true, false, false, "", "", true, "", "", "", ""],
		["Heat Detector", "4th Floor", "Apartment 445", true, false, false, "M012", "", true, "", "", "", ""],
		["Horn Strobe", "4th Floor", "Apartment 445 Entry", true, false, false, "", "", true, "", "", "", ""],
		["Ceiling Strobe", "4th Floor", "Apartment 445 Bathroom", true, false, false, "", "", true, "", "", "", ""],
		["Ceiling Horn Strobe", "4th Floor", "Apartment 445 Bedroom 1", true, false, false, "", "", true, "", "", "", ""],
		["Mini Horn", "4th Floor", "Apartment 445 Bedroom 2", true, false, false, "", "", true, "", "", "", ""],
		["Smoke Detector", "4th Floor", "Hall By Stair 4", true, false, false, "", "", true, "", "", "", ""],
		["Pull Station", "4th Floor", "Hall By Stair 4", true, false, false, "M012", "", true, "", "", "", ""],
		["Horn Strobe", "4th Floor", "Hall By Stair 4", true, false, false, "", "", true, "", "", "", ""],
		["Heat Detector", "4th Floor", "Apartment 446", true, false, false, "M012", "", true, "", "", "", ""],
		["Horn", "4th Floor", "Apartment 446", true, false, false, "", "", true, "", "", "", ""],
		["Heat Detector", "4th Floor", "Apartment 444", true, false, false, "M012", "", true, "", "", "", ""],
		["Horn", "4th Floor", "Apartment 444", true, false, false, "", "", true, "", "", "", ""],
		["Smoke Detector", "4th Floor", "Stair 4", true, false, false, "M012", "", true, "", "", "", ""],
		["Heat Detector", "4th Floor", "Apartment 442", true, false, false, "M012", "", true, "", "", "", ""],
		["Horn", "4th Floor", "Apartment 442", true, false, false, "", "", true, "", "", "", ""],
		["Heat Detector", "4th Floor", "Apartment 440", true, false, false, "M012", "", true, "", "", "", ""],
		["Horn", "4th Floor", "Apartment 440", true, false, false, "", "", true, "", "", "", ""]
	]
]
